server:
  port: 8090

spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false

dqualizer:
  messaging:
    queues:
      loadtest:
        name: loadtest
        durable: false
      k6:
        name: k6
        durable: false

    exchanges:
      loadtest:
        name: translator-loadtest
        exchangeType: TOPIC
      k6:
        name: loadtest-k6
        exchangeType: TOPIC

  dqexec:
    influx:
      host: localhost
    #    enabled: true #not a features yet
    export:
      k6:
        influx:
          organization: ${K6_INFLUXDB_ORGANIZATION:my-org}
          bucket: ${K6_INFLUXDB_BUCKET:my-bucket}
          token: ${K6_INFLUXDB_TOKEN:specialToken000}
    output:
      logs: logging
      loadtest_configurations: loadtest_configurations
#logging.level.root: debug
