server:
  port: 8090

dqualizer:
  rabbitmq:
    queues:
      loadtest: loadtest
      k6: k6
    exchanges:
      loadtest: translator-loadtest
      k6: loadtest-k6

  messaging:
    queues:
      rqaDefinitionReceiverQueue:
        name: "rqaConfiguration"

  dqexec:
    influx:
      host: localhost
      #enabled: true #not a features yet
    mysql:
      host: localhost
      port: 3306
    resilienceExecutionApi:
      host: localhost
      port: 3323
    export:
      k6:
        influx:
          organization: ${K6_INFLUXDB_ORGANIZATION:my-org}
          bucket: ${K6_INFLUXDB_BUCKET:my-bucket}
          token: ${K6_INFLUXDB_TOKEN:specialToken000}

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dqualizer