server:
  port: 8090
api:
  host: 127.0.0.1
influx:
  host: localhost

dqualizer:
  rabbitmq:
    queues:
      loadtest: loadtest
      k6: k6
    exchanges:
      loadtest: translator-loadtest
      k6: loadtest-k6
