server:
  port: 8090


dqualizer:
  rabbitmq:
    queues:
      loadtest: loadtest
      k6: k6
    exchanges:
      loadtest: translator-loadtest
      k6: loadtest-k6

  dqexec:
    influx:
      host: localhost
    #    enabled: true #not a features yet
    export:
      k6:
        influx:
          organization: ${K6_INFLUXDB_ORGANIZATION:my-org}
          bucket: ${K6_INFLUXDB_BUCKET:my-bucket}
          token: ${K6_INFLUXDB_TOKEN:specialToken000}
