server:
  port: 8090

dqualizer:
  messaging:
    queues:
      loadtest:
        name: loadtest
      rqaConfigurationProducerQueue:
        name: rqaConfigurationProducer
      k6:
        name: k6
    exchanges:
      loadtest: translator-loadtest
      k6: loadtest-k6

  dqexec:
    statsd:
      addr: ${K6_STATSD_ADDR:localhost:8125}

    output:
      logs: logging
      loadtest_configurations: loadtest_configurations
#logging.level.root: debug
