spring:
  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false

server:
  port: 8090


dqualizer:
  messaging:
    queues:
      loadTestConfigurationQueue:
        name: 'loadTestConfigurationQueue'
      resilienceTestConfigurationQueue:
        name: 'resilienceTestConfigurationQueue'

    exchanges:
      loadtest:
        name: translator-loadtest
        exchangeType: direct
        durable: true
        autoDelete: false
      k6:
        name: loadtest-k6
        exchangeType: direct
        durable: true
        autoDelete: false

  dqexec:
    influx:
      host: localhost
    #    enabled: true #not a features yet
    export:
      k6:
        influx:
          organization: ${K6_INFLUXDB_ORGANIZATION:my-org}
          bucket: ${K6_INFLUXDB_BUCKET:my-bucket}
          token: ${K6_INFLUXDB_TOKEN:specialToken000}
